### ISSUE TITLE
Execute all tests

### ISSUE THREAD

**Issue by dporr** [codecrafters-io/cli#22]
In CLI VERSION v25-c96b4d7, when running `codecrafters test` only the current/last stage is executed.
I want all the prior tests to execute to confirm my current code didn't break any of the prior assumptions/behaviors.

**Comment by rohitpaulk** [comment]
This was an intentional change to make the feedback loop faster. 

If you fail the current stage, tests will stop right there and exit early. Once you pass the current stage, you'll see tests run for the previous stages too (i.e. you won't "pass" a stage unless you pass both the current stage and all previous stage tests). 

There's also an explicit "Refactor your code" step in the UI, so once you've passed a stage you can choose to refactor and keep running tests for that step before moving to the next one. 

@dporr I know this is a significantly different compared to what we had previously, but our test times were getting pretty out of hand, especially on challenges with a lot of extensions. This felt like a good middle ground - quick feedback loop when you're working on a stage + still require passing all previous stages before you can mark a stage as complete.

**Comment by dporr** [comment]
This makes sense. Thanks!
